# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing_extensions import Literal, TypeAlias

__all__ = ["VoiceAccent"]

VoiceAccent: TypeAlias = Literal[
    "Abruzzo Italian",
    "African American English",
    "African French",
    "Arabic",
    "Arabic English",
    "Australian English",
    "Bagheli Hindi",
    "Belgian French",
    "Brazilian Portuguese",
    "British English",
    "Budapest Hungarian",
    "Bulgarian",
    "California English",
    "Camba Spanish",
    "Campania Italian",
    "Canadian English",
    "Canadian French",
    "Castilian Spanish",
    "Central Tamil",
    "Central Thai",
    "Central Vietnamese",
    "Chilean Spanish",
    "Colombian Spanish",
    "Czech",
    "Danish",
    "European Portuguese",
    "Finnish",
    "General American English",
    "High German",
    "Hindi",
    "Indian English",
    "Irish English",
    "Israeli Hebrew",
    "Istanbul Turkish",
    "Italian",
    "Jakarta Indonesian",
    "Japanese",
    "Jessore Bengali",
    "Khaleeji Arabic",
    "Konkani",
    "Korean",
    "Kyiv Ukrainian",
    "Malay",
    "Mandarin Chinese",
    "Manila Filipino",
    "Mexican Spanish",
    "Middle Eastern Arabic",
    "Midwestern American English",
    "Modern Standard Arabic",
    "Moldovan Romanian",
    "New York English",
    "New Zealand English",
    "North Kerala Malayalam",
    "Oslo Norwegian",
    "Parisian French",
    "Parsi Gujarati",
    "Peruvian Spanish",
    "Polish",
    "Powadhi Punjabi",
    "Randstad Dutch",
    "Russian",
    "Singaporean English",
    "Slovak",
    "South African English",
    "Southern American English",
    "Southern Karnataka Kannada",
    "Southern Vietnamese",
    "Standard Japanese",
    "Stockholm Swedish",
    "Swiss Standard German",
    "Tbilisi Georgian",
    "Telangana Telugu",
    "Thessaloniki Greek",
    "Zagreb Croatian",
]
