configured_endpoints: 52
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/cartesia-noahlt%2Fnoah-testing-7e36e0e6d48cc96fc040002dbdfc99da47232857ffeeed3f17e9c54b4cea89ff.yml
openapi_spec_hash: fc7c27d6f03d61265c37b77cd84b01ec
config_hash: ff284d9cde3f2c94b2a09f324e32aeb6
