configured_endpoints: 50
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/cartesia-noahlt%2Fnoah-testing-e5a73fdf4a13966d2f5a4e1e85fbeae6d29bd66c3d73e44a1fcf8bc4afe4b27f.yml
openapi_spec_hash: 0c348aaad43f7b455504fbe0b3a2e577
config_hash: 913a0a556afbb0fff5a1f8e4a43c36c1
