# This file was auto-generated by Fern from our API Definition.

from .get_voices_response import GetVoicesResponseParams
from .id_specifier import IdSpecifierParams
from .localize_dialect import LocalizeDialectParams
from .localize_voice_request import LocalizeVoiceRequestParams
from .update_voice_request import UpdateVoiceRequestParams
from .voice import VoiceParams
from .voice_metadata import VoiceMetadataParams

__all__ = [
    "GetVoicesResponseParams",
    "IdSpecifierParams",
    "LocalizeDialectParams",
    "LocalizeVoiceRequestParams",
    "UpdateVoiceRequestParams",
    "VoiceMetadataParams",
    "VoiceParams",
]
