# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...embedding.types.embedding import Embedding


class EmbeddingResponseParams(typing_extensions.TypedDict):
    embedding: Embedding
