# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...embedding.types.embedding import Embedding
from ..types.weight import Weight


class EmbeddingSpecifierParams(typing_extensions.TypedDict):
    embedding: Embedding
    weight: Weight
