# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing
from .voice import VoiceParams
import typing_extensions
from ..types.voice_id import VoiceId


class GetVoicesResponseParams(typing_extensions.TypedDict):
    data: typing.Sequence[VoiceParams]
    """
    The paginated list of Voices.
    """

    next_page: typing_extensions.NotRequired[VoiceId]
    """
    Deprecated. An ID that can be passed as `starting_after` to get the next page of Voices.
    """
