# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing
from .voice import VoiceParams


class GetVoicesResponseParams(typing_extensions.TypedDict):
    data: typing.Sequence[VoiceParams]
    """
    The paginated list of Voices.
    """

    has_more: bool
