# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.voice_id import VoiceId
from ..types.weight import Weight


class IdSpecifierParams(typing_extensions.TypedDict):
    id: VoiceId
    weight: Weight
