# This file was auto-generated by Fern from our API Definition.

import typing
from ..types.localize_english_dialect import LocalizeEnglishDialect

LocalizeDialectParams = typing.Union[LocalizeEnglishDialect]
