# This file was auto-generated by Fern from our API Definition.

import typing
from ..types.localize_english_dialect import LocalizeEnglishDialect
from ..types.localize_spanish_dialect import LocalizeSpanishDialect
from ..types.localize_portuguese_dialect import LocalizePortugueseDialect
from ..types.localize_french_dialect import LocalizeFrenchDialect

LocalizeDialectParams = typing.Union[
    LocalizeEnglishDialect, LocalizeSpanishDialect, LocalizePortugueseDialect, LocalizeFrenchDialect
]
