# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing
from .mix_voice_specifier import MixVoiceSpecifierParams


class MixVoicesRequestParams(typing_extensions.TypedDict):
    voices: typing.Sequence[MixVoiceSpecifierParams]
