# This file was auto-generated by Fern from our API Definition.

import typing
from .id_specifier import IdSpecifierParams
from .embedding_specifier import EmbeddingSpecifierParams

MixVoiceSpecifierParams = typing.Union[IdSpecifierParams, EmbeddingSpecifierParams]
