# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
from ..types.gender_presentation import GenderPresentation


class UpdateVoiceRequestParams(typing_extensions.TypedDict):
    name: str
    """
    The name of the voice.
    """

    description: str
    """
    The description of the voice.
    """

    gender: typing_extensions.NotRequired[GenderPresentation]
