# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.voice_id import VoiceId
import typing_extensions
import datetime as dt
from ...embedding.types.embedding import Embedding
from ...tts.types.supported_language import SupportedLanguage


class VoiceParams(typing_extensions.TypedDict):
    id: VoiceId
    user_id: typing_extensions.NotRequired[str]
    """
    The ID of the user who owns the voice.
    """

    is_public: bool
    """
    Whether the voice is publicly accessible.
    """

    name: str
    """
    The name of the voice.
    """

    description: str
    """
    The description of the voice.
    """

    created_at: dt.datetime
    """
    The date and time the voice was created.
    """

    embedding: Embedding
    language: SupportedLanguage
