# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.voice_id import VoiceId
import typing_extensions
from ..types.gender_presentation import GenderPresentation
import datetime as dt
from ...tts.types.supported_language import SupportedLanguage


class VoiceParams(typing_extensions.TypedDict):
    id: VoiceId
    is_owner: bool
    """
    Whether the current user is the owner of the voice.
    """

    is_public: bool
    """
    Whether the voice is publicly accessible.
    """

    name: str
    """
    The name of the voice.
    """

    description: str
    """
    The description of the voice.
    """

    gender: typing_extensions.NotRequired[GenderPresentation]
    """
    The gender of the voice, if specified.
    """

    created_at: dt.datetime
    """
    The date and time the voice was created.
    """

    is_starred: typing_extensions.NotRequired[bool]
    """
    Whether the current user has starred the voice. Only included when `expand` includes `is_starred`.
    """

    language: SupportedLanguage
