# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from .agent_call import AgentCall
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class GetCallsResponse(UniversalBaseModel):
    data: typing.List[AgentCall] = pydantic.Field()
    """
    The list of agent calls.
    """

    next_page: typing.Optional[str] = pydantic.Field(default=None)
    """
    The cursor for the next page of results.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
