# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
import datetime as dt
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class Metric(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The unique identifier for the metric.
    """

    name: str = pydantic.Field()
    """
    The name of the metric. This is a unique name that you can use to identify the metric in the CLI.
    """

    display_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The display name of the metric, if available. This is the name that is displayed in the Playground.
    """

    prompt: str = pydantic.Field()
    """
    The prompt associated with the metric, detailing the task and evaluation criteria.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    The timestamp when the metric was created.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
