# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import pydantic
import datetime as dt
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class PhoneNumber(UniversalBaseModel):
    """
    A phone number that can be used to make calls to your agent.
    """

    agent_id: str = pydantic.Field()
    """
    The ID of the agent.
    """

    number: str = pydantic.Field()
    """
    The phone number.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    The UTC timestamp when the phone number was created.
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    The UTC timestamp when the phone number was last updated.
    """

    is_cartesia_managed: bool = pydantic.Field()
    """
    Whether the phone number is managed by Cartesia. As of now, this is always true since Cartesia provisions phone numbers for you.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
