# This file was auto-generated by Fern from our API Definition.

from .types import (
    BaseVoiceId,
    CreateVoiceRequest,
    EmbeddingResponse,
    EmbeddingSpecifier,
    Gender,
    IdSpecifier,
    LocalizeDialect,
    LocalizeTargetLanguage,
    LocalizeVoiceRequest,
    MixVoiceSpecifier,
    MixVoicesRequest,
    UpdateVoiceRequest,
    Voice,
    VoiceId,
    Weight,
)

__all__ = [
    "BaseVoiceId",
    "CreateVoiceRequest",
    "EmbeddingResponse",
    "EmbeddingSpecifier",
    "Gender",
    "IdSpecifier",
    "LocalizeDialect",
    "LocalizeTargetLanguage",
    "LocalizeVoiceRequest",
    "MixVoiceSpecifier",
    "MixVoicesRequest",
    "UpdateVoiceRequest",
    "Voice",
    "VoiceId",
    "Weight",
]
