# This file was auto-generated by Fern from our API Definition.

from .create_pronunciation_dict_request import CreatePronunciationDictRequestParams
from .paginated_pronunciation_dicts import PaginatedPronunciationDictsParams
from .pronunciation_dict import PronunciationDictParams
from .pronunciation_dict_item import PronunciationDictItemParams
from .update_pronunciation_dict_request import UpdatePronunciationDictRequestParams

__all__ = [
    "CreatePronunciationDictRequestParams",
    "PaginatedPronunciationDictsParams",
    "PronunciationDictItemParams",
    "PronunciationDictParams",
    "UpdatePronunciationDictRequestParams",
]
