# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
import typing
from .pronunciation_dict_item import PronunciationDictItemParams


class CreatePronunciationDictRequestParams(typing_extensions.TypedDict):
    """
    Request to create a new pronunciation dictionary
    """

    name: str
    """
    Name for the new pronunciation dictionary
    """

    items: typing_extensions.NotRequired[typing.Sequence[PronunciationDictItemParams]]
    """
    Optional initial list of pronunciation mappings
    """
