# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class PronunciationDictItemParams(typing_extensions.TypedDict):
    """
    A pronunciation dictionary item mapping text to a custom pronunciation
    """

    text: str
    """
    The original text to be replaced
    """

    alias: str
    """
    A phonetic representation or text to be said in place of the original text
    """
