# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions


class PronunciationDictItemParams(typing_extensions.TypedDict):
    """
    A pronunciation dictionary item mapping text to a custom pronunciation.
    """

    text: str
    """
    The original text to be replaced. All lowercase entries are case-insensitive and title case of the word will be handled automatically. For example, if your entry is "tomato", you do not need to make a new entry for "Tomato". However, entries with mixed case or non-Latin characters are case-sensitive, so if your entry is "LaTeX", it will not apply to "latex".
    """

    pronunciation: str
    """
    A phonetic representation or text to be said in place of the original text. The pronunciation can be at most 100 characters.
    """

    alias: typing_extensions.NotRequired[str]
    """
    A phonetic representation or text to be said in place of the original text. The alias can be at most 100 characters.
    """
