# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
import typing
from .pronunciation_dict_item import PronunciationDictItemParams


class UpdatePronunciationDictRequestParams(typing_extensions.TypedDict):
    """
    Request to update an existing pronunciation dictionary
    """

    name: typing_extensions.NotRequired[str]
    """
    New name for the pronunciation dictionary
    """

    description: typing_extensions.NotRequired[str]
    """
    New description for the pronunciation dictionary
    """

    items: typing_extensions.NotRequired[typing.Sequence[PronunciationDictItemParams]]
    """
    Updated list of unique pronunciation mappings
    """
