# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from .stt_auto_finalize_model import STTAutoFinalizeModel as STTAutoFinalizeModel
from .stt_manual_finalize_model import STTManualFinalizeModel as STTManualFinalizeModel
from .stt_auto_finalize_turn_end import STTAutoFinalizeTurnEnd as STTAutoFinalizeTurnEnd
from .stt_auto_finalize_connected import STTAutoFinalizeConnected as STTAutoFinalizeConnected
from .stt_auto_finalize_turn_start import STTAutoFinalizeTurnStart as STTAutoFinalizeTurnStart
from .stt_auto_finalize_turn_resume import STTAutoFinalizeTurnResume as STTAutoFinalizeTurnResume
from .stt_auto_finalize_turn_update import STTAutoFinalizeTurnUpdate as STTAutoFinalizeTurnUpdate
from .auto_finalize_websocket_params import AutoFinalizeWebsocketParams as AutoFinalizeWebsocketParams
from .stt_auto_finalize_close_command import STTAutoFinalizeCloseCommand as STTAutoFinalizeCloseCommand
from .manual_finalize_websocket_params import ManualFinalizeWebsocketParams as ManualFinalizeWebsocketParams
from .stt_auto_finalize_config_command import STTAutoFinalizeConfigCommand as STTAutoFinalizeConfigCommand
from .stt_auto_finalize_turn_eager_end import STTAutoFinalizeTurnEagerEnd as STTAutoFinalizeTurnEagerEnd
from .stt_manual_finalize_done_response import STTManualFinalizeDoneResponse as STTManualFinalizeDoneResponse
from .stt_auto_finalize_websocket_request import STTAutoFinalizeWebsocketRequest as STTAutoFinalizeWebsocketRequest
from .stt_auto_finalize_websocket_response import STTAutoFinalizeWebsocketResponse as STTAutoFinalizeWebsocketResponse
from .stt_auto_finalize_close_command_param import STTAutoFinalizeCloseCommandParam as STTAutoFinalizeCloseCommandParam
from .stt_manual_finalize_websocket_request import (
    STTManualFinalizeWebsocketRequest as STTManualFinalizeWebsocketRequest,
)
from .stt_auto_finalize_config_command_param import (
    STTAutoFinalizeConfigCommandParam as STTAutoFinalizeConfigCommandParam,
)
from .stt_manual_finalize_websocket_response import (
    STTManualFinalizeWebsocketResponse as STTManualFinalizeWebsocketResponse,
)
from .stt_manual_finalize_flush_done_response import (
    STTManualFinalizeFlushDoneResponse as STTManualFinalizeFlushDoneResponse,
)
from .stt_manual_finalize_transcript_response import (
    STTManualFinalizeTranscriptResponse as STTManualFinalizeTranscriptResponse,
)
from .stt_auto_finalize_websocket_request_param import (
    STTAutoFinalizeWebsocketRequestParam as STTAutoFinalizeWebsocketRequestParam,
)
