# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class CreateFineTuneRequest(UniversalBaseModel):
    """
    Request to create a new fine-tune
    """

    name: str = pydantic.Field()
    """
    Name for the new fine-tune
    """

    description: str = pydantic.Field()
    """
    Description for the fine-tune
    """

    language: str = pydantic.Field()
    """
    Language code for the fine-tune
    """

    model_id: str = pydantic.Field()
    """
    Base model ID to fine-tune from
    """

    dataset: str = pydantic.Field()
    """
    Dataset ID containing training files
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
