# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from .fine_tune import FineTune
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class PaginatedFineTunes(UniversalBaseModel):
    """
    Paginated list of fine-tunes
    """

    data: typing.List[FineTune] = pydantic.Field()
    """
    List of fine-tune objects
    """

    has_more: bool = pydantic.Field()
    """
    Whether there are more fine-tunes available
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
