# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class DoneMessageParams(typing_extensions.TypedDict):
    """
    Acknowledgment message sent in response to a `done` command, indicating that the session is complete and the WebSocket will close.
    """

    request_id: str
    """
    Unique identifier for this transcription session.
    """
