# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class FlushDoneMessageParams(typing_extensions.TypedDict):
    """
    Acknowledgment message sent in response to a `finalize` command, indicating that all buffered audio has been flushed and processed.
    """

    request_id: str
    """
    Unique identifier for this transcription session.
    """
