# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class TranscriptionWordParams(typing_extensions.TypedDict):
    word: str
    """
    The transcribed word.
    """

    start: float
    """
    Start time of the word in seconds.
    """

    end: float
    """
    End time of the word in seconds.
    """
