# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions


class TranscriptionResponseParams(typing_extensions.TypedDict):
    text: str
    """
    The transcribed text.
    """

    language: typing_extensions.NotRequired[str]
    """
    The detected or specified language of the input audio.
    """

    duration: typing_extensions.NotRequired[float]
    """
    The duration of the input audio in seconds.
    """
