# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class CreateFineTuneRequestParams(typing_extensions.TypedDict):
    """
    Request to create a new fine-tune
    """

    name: str
    """
    Name for the new fine-tune
    """

    description: str
    """
    Description for the fine-tune
    """

    language: str
    """
    Language code for the fine-tune
    """

    model_id: str
    """
    Base model ID to fine-tune from
    """

    dataset: str
    """
    Dataset ID containing training files
    """
