# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing
from .fine_tune import FineTuneParams


class PaginatedFineTunesParams(typing_extensions.TypedDict):
    """
    Paginated list of fine-tunes
    """

    data: typing.Sequence[FineTuneParams]
    """
    List of fine-tune objects
    """

    has_more: bool
    """
    Whether there are more fine-tunes available
    """
