# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing
from ...voices.requests.voice import VoiceParams


class PaginatedVoicesParams(typing_extensions.TypedDict):
    """
    Paginated list of voices created from a fine-tune
    """

    data: typing.Sequence[VoiceParams]
    """
    List of voice objects
    """

    has_more: bool
    """
    Whether there are more voices available
    """
