# This file was auto-generated by Fern from our API Definition.

import typing

LocalizeTargetLanguage = typing.Union[
    typing.Literal["en", "de", "es", "fr", "ja", "pt", "zh", "hi", "it", "ko", "nl", "pl", "ru", "sv", "tr"], typing.Any
]
