# This file was auto-generated by Fern from our API Definition.

import typing
from .localize_english_dialect import LocalizeEnglishDialect
from .localize_spanish_dialect import LocalizeSpanishDialect
from .localize_portuguese_dialect import LocalizePortugueseDialect
from .localize_french_dialect import LocalizeFrenchDialect

LocalizeDialect = typing.Union[
    LocalizeEnglishDialect, LocalizeSpanishDialect, LocalizePortugueseDialect, LocalizeFrenchDialect
]
