# This file was auto-generated by Fern from our API Definition.

import typing
from .id_specifier import IdSpecifier
from .embedding_specifier import EmbeddingSpecifier

MixVoiceSpecifier = typing.Union[IdSpecifier, EmbeddingSpecifier]
