# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from .gender_presentation import GenderPresentation
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class UpdateVoiceRequest(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    The name of the voice.
    """

    description: str = pydantic.Field()
    """
    The description of the voice.
    """

    gender: typing.Optional[GenderPresentation] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
