# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class TokenResponseParams(typing_extensions.TypedDict):
    token: str
    """
    The generated Access Token.
    """
