# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
import datetime as dt
from ...voices.types.voice_id import VoiceId
from .git_repository import GitRepositoryParams
import typing
from .phone_number_summary import PhoneNumberSummaryParams


class AgentSummaryParams(typing_extensions.TypedDict):
    """
    A summary of essential information about an agent.
    """

    id: str
    """
    The ID of the agent.
    """

    name: str
    """
    The unique name of the agent, which can be used to identify the agent in the CLI.
    """

    description: typing_extensions.NotRequired[str]
    """
    A brief description of the agent.
    """

    created_at: dt.datetime
    """
    The date and time when the agent was created.
    """

    updated_at: dt.datetime
    """
    The date and time when the agent was last updated.
    """

    tts_voice: VoiceId
    """
    The text-to-speech voice used by the agent.
    """

    tts_language: str
    """
    The language used for text-to-speech by the agent.
    """

    webhook_id: typing_extensions.NotRequired[str]
    """
    The identifier for the webhook associated with the agent. Add or customize a webhook to your agent to receive events when calls are made to your agent via the Playground.
    """

    deleted_at: typing_extensions.NotRequired[dt.datetime]
    """
    The date and time when the agent was deleted, if applicable.
    """

    git_repository: typing_extensions.NotRequired[GitRepositoryParams]
    """
    The Git repository associated with the agent.
    """

    git_deploy_branch: typing_extensions.NotRequired[str]
    """
    The branch of the Git repository used for deployment.
    """

    phone_numbers: typing_extensions.NotRequired[typing.Sequence[PhoneNumberSummaryParams]]
    """
    The phone numbers associated with the agent. Currently, you can only have one phone number per agent.
    """

    has_text_to_agent_run: bool
    """
    Whether the agent has a text-to-agent run.
    """

    deployment_count: int
    """
    The number of deployments associated with the agent.
    """
