# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
import datetime as dt
import typing
from .agent_transcript import AgentTranscriptParams
from .telephony_params import TelephonyParamsParams
from ..types.agent_call_status import AgentCallStatus


class AgentCallParams(typing_extensions.TypedDict):
    id: str
    """
    The unique identifier for the agent call.
    """

    agent_id: str
    """
    The identifier of the agent associated with the call.
    """

    start_time: typing_extensions.NotRequired[dt.datetime]
    """
    The start time of the agent call.
    """

    end_time: typing_extensions.NotRequired[dt.datetime]
    """
    The end time of the agent call.
    """

    transcript: typing_extensions.NotRequired[typing.Sequence[AgentTranscriptParams]]
    """
    The transcript of the agent call.
    """

    telephony_params: typing_extensions.NotRequired[TelephonyParamsParams]
    """
    The telephony parameters associated with the call when the call is made via phone.
    """

    summary: typing_extensions.NotRequired[str]
    """
    A summary of the agent call. This is a brief summary of the call that is generated by Cartesia.
    """

    status: AgentCallStatus
    """
    The status of the agent call.
    """

    error_message: typing_extensions.NotRequired[str]
    """
    The error message, if any, associated with the call.
    """

    deployment_id: typing_extensions.NotRequired[str]
    """
    The deployment identifier associated with the call.
    """
