# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
import typing
import datetime as dt


class AgentTemplateParams(typing_extensions.TypedDict):
    id: str
    """
    The ID of the agent template.
    """

    name: str
    """
    The name of the agent template.
    """

    description: typing_extensions.NotRequired[str]
    """
    The description of the agent template.
    """

    repo_url: str
    """
    The URL of the Git repository associated with the agent template.
    """

    root_dir: str
    """
    The root directory of the agent template.
    """

    required_env_vars: typing_extensions.NotRequired[typing.Sequence[str]]
    """
    The required environment variables for the agent template.
    """

    dependencies: typing_extensions.NotRequired[typing.Sequence[str]]
    """
    The dependencies of the agent template.
    """

    owner_id: str
    """
    The ID of the owner of the agent template.
    """

    created_at: dt.datetime
    """
    The UTC timestamp when the agent template was created.
    """

    updated_at: dt.datetime
    """
    The UTC timestamp when the agent template was last updated.
    """
