# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions


class CreateMetricRequestParams(typing_extensions.TypedDict):
    name: str
    """
    The name of the metric. This must be a unique name that only allows lower case letters, numbers, and the characters _, -, and .
    """

    display_name: typing_extensions.NotRequired[str]
    """
    The display name of the metric.
    """

    prompt: str
    """
    The prompt associated with the metric, detailing the task and evaluation criteria.
    """
