# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import datetime as dt
import typing_extensions


class DeploymentParams(typing_extensions.TypedDict):
    id: str
    """
    The unique identifier for the deployment.
    """

    agent_id: str
    """
    The ID of the agent associated with this deployment.
    """

    status: str
    """
    The current status of the deployment. It can be `queued`, `inactive`, `deploy_error`, `skipped`, `build_error`, `building`, or `deployed`.
    """

    is_pinned: bool
    """
    Marks that this deployment is the active deployment for its associated `agent_id`. Only one deployment per agent can be pinned at a time. Deployments can be pinned even if they are not live or failed.
    """

    is_live: bool
    """
    True if this deployment is the live production deployment for its associated `agent_id`. Only one deployment per agent can be live at a time.
    """

    env_var_collection_id: str
    """
    The ID of the environment variable collection associated with this deployment.
    """

    source_code_file_id: str
    """
    The ID of the source code file associated with this deployment.
    """

    git_commit_hash: str
    """
    The commit hash of the Git repository for this deployment.
    """

    created_at: dt.datetime
    """
    The UTC timestamp when the deployment was created.
    """

    updated_at: dt.datetime
    """
    The UTC timestamp when the deployment was last updated.
    """

    build_completed_at: dt.datetime
    """
    The UTC timestamp when the build was completed.
    """

    build_error: typing_extensions.NotRequired[str]
    """
    Any error that occurred during the build process.
    """

    build_logs: str
    """
    Logs generated during the build process of the deployment.
    """

    build_started_at: dt.datetime
    """
    The UTC timestamp when the build process started.
    """

    deployment_started_at: dt.datetime
    """
    The UTC timestamp when the deployment process started.
    """

    deployment_completed_at: dt.datetime
    """
    The UTC timestamp when the deployment process was completed.
    """

    deployment_error: typing_extensions.NotRequired[str]
    """
    Any error that occurred during the deployment process.
    """
