# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing
from .agent_call import AgentCallParams
import typing_extensions


class GetCallsResponseParams(typing_extensions.TypedDict):
    data: typing.Sequence[AgentCallParams]
    """
    The list of agent calls.
    """

    next_page: typing_extensions.NotRequired[str]
    """
    The cursor for the next page of results.
    """
