# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing
from .agent_template import AgentTemplateParams


class GetTemplatesResponseParams(typing_extensions.TypedDict):
    templates: typing.Sequence[AgentTemplateParams]
    """
    List of agent templates.
    """
