# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing
from .agent_summary import AgentSummaryParams


class GetAgentsResponseParams(typing_extensions.TypedDict):
    summaries: typing.Sequence[AgentSummaryParams]
    """
    The summaries of the agents.
    """
