# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class GitRepositoryParams(typing_extensions.TypedDict):
    provider: str
    """
    The provider of the Git repository, e.g., GitHub.
    """

    account: str
    """
    The account name associated with the Git repository.
    """

    name: str
    """
    The name of the Git repository.
    """
