# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing
from .metric import MetricParams
import typing_extensions


class ListMetricsResponseParams(typing_extensions.TypedDict):
    data: typing.Sequence[MetricParams]
    """
    List of metrics.
    """

    has_more: bool
    """
    Whether there are more metrics to fetch (using `starting_after=id`, where id is the ID of the last Metric in the current response).
    """

    next_page: typing_extensions.NotRequired[str]
    """
    The ID of the last Metric in the current response as a cursor for the next page of results.
    """
