# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing


class LogEventParams(typing_extensions.TypedDict):
    event: str
    """
    The event name.
    """

    metadata: typing.Dict[str, str]
    """
    Additional metadata associated with the event.
    """

    timestamp: float
    """
    The timestamp when the event was received relative to the start of the call.
    """
