# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class LogMetricParams(typing_extensions.TypedDict):
    name: str
    """
    The name of the metric.
    """

    value: float
    """
    The value of the metric.
    """

    timestamp: float
    """
    The timestamp when the metric was received relative to the start of the call.
    """
