# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
import datetime as dt


class MetricParams(typing_extensions.TypedDict):
    id: str
    """
    The unique identifier for the metric.
    """

    name: str
    """
    The name of the metric. This is a unique name that you can use to identify the metric in the CLI.
    """

    display_name: typing_extensions.NotRequired[str]
    """
    The display name of the metric, if available. This is the name that is displayed in the Playground.
    """

    prompt: str
    """
    The prompt associated with the metric, detailing the task and evaluation criteria.
    """

    created_at: dt.datetime
    """
    The timestamp when the metric was created.
    """
