# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import datetime as dt


class PhoneNumberParams(typing_extensions.TypedDict):
    """
    A phone number that can be used to make calls to your agent.
    """

    agent_id: str
    """
    The ID of the agent.
    """

    number: str
    """
    The phone number.
    """

    created_at: dt.datetime
    """
    The UTC timestamp when the phone number was created.
    """

    updated_at: dt.datetime
    """
    The UTC timestamp when the phone number was last updated.
    """

    is_cartesia_managed: bool
    """
    Whether the phone number is managed by Cartesia. As of now, this is always true since Cartesia provisions phone numbers for you.
    """
