# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
from ...core.serialization import FieldMetadata


class TelephonyParamsParams(typing_extensions.TypedDict):
    """
    The telephony parameters associated with the call when the call is made via a phone. More details can also be returned depending on the provider.
    """

    to: str
    """
    The phone number of the caller.
    """

    from_: typing_extensions.Annotated[str, FieldMetadata(alias="from")]
    """
    The phone number of the agent.
    """
