# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class TextChunkParams(typing_extensions.TypedDict):
    text: str
    """
    The text content of the chunk.
    """

    start_timestamp: float
    """
    The starting timestamp of the text chunk in seconds relative to the start of the call.
    """
