# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing


class ToolCallParams(typing_extensions.TypedDict):
    id: str
    """
    The unique identifier for the tool call.
    """

    name: str
    """
    The name of the tool that was called.
    """

    arguments: typing.Dict[str, str]
    """
    The arguments passed to the tool.
    """
