# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
from ...voices.types.voice_id import VoiceId


class UpdateAgentRequestParams(typing_extensions.TypedDict):
    name: typing_extensions.NotRequired[str]
    """
    The name of the agent.
    """

    description: typing_extensions.NotRequired[str]
    """
    The description of the agent.
    """

    tts_voice: typing_extensions.NotRequired[VoiceId]
    """
    The voice to use for text-to-speech.
    """

    tts_language: typing_extensions.NotRequired[str]
    """
    The language to use for text-to-speech.
    """
