# This file was auto-generated by Fern from our API Definition.

from .create_pronunciation_dict_request import CreatePronunciationDictRequest
from .paginated_pronunciation_dicts import PaginatedPronunciationDicts
from .pronunciation_dict import PronunciationDict
from .pronunciation_dict_item import PronunciationDictItem
from .update_pronunciation_dict_request import UpdatePronunciationDictRequest

__all__ = [
    "CreatePronunciationDictRequest",
    "PaginatedPronunciationDicts",
    "PronunciationDict",
    "PronunciationDictItem",
    "UpdatePronunciationDictRequest",
]
