# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class PronunciationDictItem(UniversalBaseModel):
    """
    A pronunciation dictionary item mapping text to a custom pronunciation
    """

    text: str = pydantic.Field()
    """
    The original text to be replaced
    """

    alias: str = pydantic.Field()
    """
    A phonetic representation or text to be said in place of the original text
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
