# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class ExperimentalModelControls(UniversalBaseModel):
    """
    These controls are **experimental** and subject to breaking changes.
    """

    accent_localization: typing.Optional[int] = pydantic.Field(default=None)
    """
    Toggle accent localization: 0 (disabled, default) or 1 (enabled).
    When enabled, the voice adapts to match the transcript language's accent while preserving vocal characteristics. When disabled, maintains the original voice accent.
    For more information, see [Localize Voices](/build-with-sonic/capabilities/localize-voices).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
