# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .experimental_model_controls import ExperimentalModelControls
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class GenerationConfig(UniversalBaseModel):
    """
    Configure the various attributes of the generated speech. These controls are only available for `sonic-3-preview` and will have no effect on earlier models.
    """

    volume: typing.Optional[float] = pydantic.Field(default=None)
    """
    Adjust the volume of the generated speech between -1.0 (softer) and 1.0 (louder). 0.0 is the default volume.
    """

    speed: typing.Optional[float] = pydantic.Field(default=None)
    """
    Adjust the speed of the generated speech between -1.0 (slower) and 1.0 (faster). 0.0 is the default speed.
    """

    experimental: typing.Optional[ExperimentalModelControls] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
