# This file was auto-generated by Fern from our API Definition.

import typing
from .numerical_specifier import NumericalSpecifier
from .natural_specifier import NaturalSpecifier

Speed = typing.Union[NumericalSpecifier, NaturalSpecifier]
