# This file was auto-generated by Fern from our API Definition.

import typing
from .tts_request_id_specifier import TtsRequestIdSpecifier
from .tts_request_embedding_specifier import TtsRequestEmbeddingSpecifier

TtsRequestVoiceSpecifier = typing.Union[TtsRequestIdSpecifier, TtsRequestEmbeddingSpecifier]
