# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from .raw_encoding import RawEncoding
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class WebSocketRawOutputFormat(UniversalBaseModel):
    container: typing.Literal["raw"] = "raw"
    encoding: RawEncoding
    sample_rate: int = pydantic.Field()
    """
    The sample rate of the audio in Hz. Supported sample rates are 8000, 16000, 22050, 24000, 44100, 48000.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
