# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
from .experimental_model_controls import ExperimentalModelControlsParams


class GenerationConfigParams(typing_extensions.TypedDict):
    """
    Configure the various attributes of the generated speech. These controls are only available for `sonic-3-preview` and will have no effect on earlier models.
    """

    volume: typing_extensions.NotRequired[float]
    """
    Adjust the volume of the generated speech between -1.0 (softer) and 1.0 (louder). 0.0 is the default volume.
    """

    speed: typing_extensions.NotRequired[float]
    """
    Adjust the speed of the generated speech between -1.0 (slower) and 1.0 (faster). 0.0 is the default speed.
    """

    experimental: typing_extensions.NotRequired[ExperimentalModelControlsParams]
