# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class Mp3OutputFormatParams(typing_extensions.TypedDict):
    sample_rate: int
    """
    The sample rate of the audio in Hz. Supported sample rates are 8000, 16000, 22050, 24000, 44100, 48000.
    """

    bit_rate: int
    """
    The bit rate of the audio in bits per second. Supported bit rates are 32000, 64000, 96000, 128000, 192000.
    """
