# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing


class PhonemeTimestampsParams(typing_extensions.TypedDict):
    phonemes: typing.Sequence[str]
    start: typing.Sequence[float]
    end: typing.Sequence[float]
