# This file was auto-generated by Fern from our API Definition.

import typing
from ..types.numerical_specifier import NumericalSpecifier
from ..types.natural_specifier import NaturalSpecifier

SpeedParams = typing.Union[NumericalSpecifier, NaturalSpecifier]
