# This file was auto-generated by Fern from our API Definition.

import typing
from .tts_request_id_specifier import TtsRequestIdSpecifierParams
from .tts_request_embedding_specifier import TtsRequestEmbeddingSpecifierParams

TtsRequestVoiceSpecifierParams = typing.Union[TtsRequestIdSpecifierParams, TtsRequestEmbeddingSpecifierParams]
