# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing
from ...voices.types.voice_id import VoiceId


class TtsRequestVoiceSpecifierParams(typing_extensions.TypedDict):
    mode: typing.Literal["id"]
    id: VoiceId
