# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing
from ..types.raw_encoding import RawEncoding


class WebSocketRawOutputFormatParams(typing_extensions.TypedDict):
    container: typing.Literal["raw"]
    encoding: RawEncoding
    sample_rate: int
