# This file was auto-generated by Fern from our API Definition.

from .web_socket_base_response import WebSocketBaseResponseParams
import typing_extensions
from .word_timestamps import WordTimestampsParams


class WebSocketTimestampsResponseParams(WebSocketBaseResponseParams):
    word_timestamps: typing_extensions.NotRequired[WordTimestampsParams]
