# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
from .output_format import OutputFormatParams
from .tts_request_voice_specifier import TtsRequestVoiceSpecifierParams
from ...core.serialization import FieldMetadata


class WebSocketTtsRequestParams(typing_extensions.TypedDict):
    model_id: str
    """
    The ID of the model to use for the generation. See [Models](/build-with-sonic/models) for available models.
    """

    output_format: typing_extensions.NotRequired[OutputFormatParams]
    transcript: typing_extensions.NotRequired[str]
    voice: TtsRequestVoiceSpecifierParams
    duration: typing_extensions.NotRequired[int]
    language: typing_extensions.NotRequired[str]
    add_timestamps: typing_extensions.NotRequired[bool]
    add_phoneme_timestamps: typing_extensions.NotRequired[bool]
    continue_: typing_extensions.NotRequired[typing_extensions.Annotated[bool, FieldMetadata(alias="continue")]]
    context_id: typing_extensions.NotRequired[str]
