# This file was auto-generated by Fern from our API Definition.

import typing
from .generation_request import GenerationRequestParams
from .cancel_context_request import CancelContextRequestParams

WebSocketRequestParams = typing.Union[GenerationRequestParams, CancelContextRequestParams]
