# This file was auto-generated by Fern from our API Definition.

from .web_socket_base_response import WebSocketBaseResponseParams


class WebSocketErrorResponseParams(WebSocketBaseResponseParams):
    error: str
