# This file was auto-generated by Fern from our API Definition.

from .web_socket_base_response import WebSocketBaseResponseParams
import typing_extensions
from ..types.flush_id import FlushId


class WebSocketChunkResponseParams(WebSocketBaseResponseParams):
    data: str
    step_time: float
    flush_id: typing_extensions.NotRequired[FlushId]
