# This file was auto-generated by Fern from our API Definition.

from .web_socket_base_response import WebSocketBaseResponseParams
import typing_extensions
from .phoneme_timestamps import PhonemeTimestampsParams


class WebSocketPhonemeTimestampsResponseParams(WebSocketBaseResponseParams):
    phoneme_timestamps: typing_extensions.NotRequired[PhonemeTimestampsParams]
