# This file was auto-generated by Fern from our API Definition.

from .web_socket_base_response import WebSocketBaseResponseParams
from ..types.flush_id import FlushId


class WebSocketFlushDoneResponseParams(WebSocketBaseResponseParams):
    flush_id: FlushId
    flush_done: bool
