# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions


class WebSocketStreamOptionsParams(typing_extensions.TypedDict):
    timeout: typing_extensions.NotRequired[float]
