# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
from ..types.context_id import ContextId


class WebSocketBaseResponseParams(typing_extensions.TypedDict):
    context_id: typing_extensions.NotRequired[ContextId]
    status_code: int
    done: bool
